# Generated by Django 3.2.7 on 2022-05-17 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0003_diagrams_xml'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='diagrams.diagrams')),
            ],
        ),
    ]
